locale/core.yml
Der Text passt nicht auf den button, einfach antworten sollte deskriptiv
genug sein
=> Overlap fix

locale/core.yml
Kleinere Übersetzungen von Texten und Hinweisen die noch auf englisch verfasst waren.
(Erster Pull Request, hoffe es passt alles)
=> Kleinere Übersetzungen 

locale/core.yml
Changed a lot of typos. Most common errors fixed:
* Inconsequential hyphenation
* dass/das
* Syntax problems
=> Many typos and syntax fixes

CHANGELOG.md
This is a draft of changelog for the `1.4.1` release.
Here you can find all related translations changes: [1.4.0...master](https://github.com/flarum-lang/german/compare/1.4.0...master).
> 
> You should [approve](https://github.com/rob006-software/flarum-translations/wiki/How-to-approve-release-pull-request) this pull request instead. After approving, I will automatically update it (release date needs to be adjusted), merge, and tag a new release.
<details>
**Updated translations for extensions**:
* [`clarkwinkelmann/flarum-ext-first-post-approval`](https://github.com/clarkwinkelmann/flarum-ext-first-post-approval)
* [`nearata/flarum-ext-minecraft-avatars`](https://github.com/Nearata/flarum-ext …
=> Release `1.4.1`

CHANGELOG.md
This is a draft of changelog for the `1.4.2` release.
Here you can find all related translations changes: [1.4.1...master](https://github.com/flarum-lang/german/compare/1.4.1...master).
> 
<details> …
=> Release `1.4.2`

CHANGELOG.md
This is a draft of changelog for the `1.4.3` release.
Here you can find all related translations changes: [1.4.2...master](https://github.com/flarum-lang/german/compare/1.4.2...master).
> 
<details>
* …
=> Release `1.4.3`

CHANGELOG.md
This is a draft of changelog for the `1.4.4` release.
Here you can find all related translations changes: [1.4.3...master](https://github.com/flarum-lang/german/compare/1.4.3...master).
> 
<details> …
=> Release `1.4.4`

CHANGELOG.md
This is a draft of changelog for the `1.4.5` release.
Here you can find all related translations changes: [1.4.4...master](https://github.com/flarum-lang/german/compare/1.4.4...master).
> 
<details> …
=> Release `1.4.5`

CHANGELOG.md
This is a draft of changelog for the `1.4.7` release.
Here you can find all related translations changes: [1.4.6...master](https://github.com/flarum-lang/german/compare/1.4.6...master).
> 
<details> …
=> Release `1.4.7`

CHANGELOG.md
This is a draft of changelog for the `1.4.8` release.
Here you can find all related translations changes: [1.4.7...master](https://github.com/flarum-lang/german/compare/1.4.7...master).
> 
<details>
Alle Änderungen: …
=> Release `1.4.8`

CHANGELOG.md
This is a draft of changelog for the `1.4.9` release.
Here you can find all related translations changes: [1.4.8...master](https://github.com/flarum-lang/german/compare/1.4.8...master).
> 
<details> …
=> Release `1.4.9`

CHANGELOG.md
This is a draft of changelog for the `1.4.10` release.
Here you can find all related translations changes: [1.4.9...master](https://github.com/flarum-lang/german/compare/1.4.9...master).
> 
<details>
* Validation Übersetzungen …
=> Release `1.4.10`

CHANGELOG.md
This is a draft of changelog for the `1.6.0` release.
Here you can find all related translations changes: [1.5.0...master](https://github.com/flarum-lang/german/compare/1.5.0...master).
> 
<details>
* …
=> Release `1.6.0`

CHANGELOG.md
This is a draft of changelog for the `1.8.0` release.
Here you can find all related translations changes: [1.7.0...master](https://github.com/flarum-lang/german/compare/1.7.0...master).
> 
<details>
* …
=> Release `1.8.0`

CHANGELOG.md
This is a draft of changelog for the `1.8.1` release.
Here you can find all related translations changes: [1.8.0...master](https://github.com/flarum-lang/german/compare/1.8.0...master).
> 
<details>
* [`fof/polls`](https://github.com/FriendsOfFlarum/polls) …
=> Release `1.8.1`

CHANGELOG.md
This is a draft of changelog for the `1.8.2` release.
Here you can find all related translations changes: [1.8.1...master](https://github.com/flarum-lang/german/compare/1.8.1...master).
> 
<details>
* [`fof/terms`](https://github.com/FriendsOfFlarum/terms) …
=> Release `1.8.2`

CHANGELOG.md
This is a draft of changelog for the `1.8.3` release.
Here you can find all related translations changes: [1.8.2...master](https://github.com/flarum-lang/german/compare/1.8.2...master).
> 
<details>
* …
=> Release `1.8.3`

CHANGELOG.md
This is a draft of changelog for the `1.9.0` release.
Here you can find all related translations changes: [1.8.3...master](https://github.com/flarum-lang/german/compare/1.8.3...master).
> 
<details>
* …
=> Release `1.9.0`

CHANGELOG.md
This is a draft of changelog for the `1.10.0` release.
Here you can find all related translations changes: [1.9.0...master](https://github.com/flarum-lang/german/compare/1.9.0...master).
> 
<details>
* …
=> Release `1.10.0`

CHANGELOG.md
This is a draft of changelog for the `1.11.0` release.
Here you can find all related translations changes: [1.10.0...master](https://github.com/flarum-lang/german/compare/1.10.0...master).
> 
<details>
* …
=> Release `1.11.0`

CHANGELOG.md
This is a draft of changelog for the `1.14.0` release.
Here you can find all related translations changes: [1.13.0...master](https://github.com/flarum-lang/german/compare/1.13.0...master).
> 
<details>
* …
=> Release `1.14.0`

CHANGELOG.md
This is a draft of changelog for the `1.15.0` release.
Here you can find all related translations changes: [1.14.0...master](https://github.com/flarum-lang/german/compare/1.14.0...master).
> 
<details>
* …
=> Release `1.15.0`

CHANGELOG.md
This is a draft of changelog for the `1.15.1` release.
Here you can find all related translations changes: [1.15.0...master](https://github.com/flarum-lang/german/compare/1.15.0...master).
> 
<details> …
=> Release `1.15.1`

CHANGELOG.md
This is a draft of changelog for the `1.16.0` release.
Here you can find all related translations changes: [1.15.1...master](https://github.com/flarum-lang/german/compare/1.15.1...master).
> 
<details>
* [`flarum/gdpr`](https://github.com/flarum/gdpr) …
=> Release `1.16.0`

CHANGELOG.md
This is a draft of changelog for the `1.16.1` release.
Here you can find all related translations changes: [1.16.0...master](https://github.com/flarum-lang/german/compare/1.16.0...master).
> 
<details>
* [`flarum/emoji`](https://github.com/flarum/emoji)
* …
=> Release `1.16.1`

CHANGELOG.md
This is a draft of changelog for the `1.17.0` release.
Here you can find all related translations changes: [1.16.1...master](https://github.com/flarum-lang/german/compare/1.16.1...master).
> 
<details>
* …
=> Release `1.17.0`

CHANGELOG.md
This is a draft of changelog for the `1.18.0` release.
Here you can find all related translations changes: [1.17.0...master](https://github.com/flarum-lang/german/compare/1.17.0...master).
> 
<details>
* …
=> Release `1.18.0`

CHANGELOG.md
This is a draft of changelog for the `1.18.1` release.
Here you can find all related translations changes: [1.18.0...master](https://github.com/flarum-lang/german/compare/1.18.0...master).
> 
<details>
* …
=> Release `1.18.1`

CHANGELOG.md
This is a draft of changelog for the `1.19.0` release.
Here you can find all related translations changes: [1.18.1...master](https://github.com/flarum-lang/german/compare/1.18.1...master).
> 
<details>
* …
=> Release `1.19.0`

CHANGELOG.md
This is a draft of changelog for the `1.20.0` release.
Here you can find all related translations changes: [1.19.1...master](https://github.com/flarum-lang/german/compare/1.19.1...master).
> 
<details>
* …
=> Release `1.20.0`
